name: kenna-toolkit
# syntax for a schedule. Uncomment next 3 lines to use schedules. This sample will run everyday at 5:45 UTC
#on: 
#  schedule:
#    - cron: "45 5 * * *"   
    
# default syntax is an on-demand task that can be manually initiated    
on: workflow_dispatch
jobs:
  my_toolkit_job:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_KEY }}
    steps:
      - run: docker pull kennasecurity/toolkit && docker run -i kennasecurity/toolkit task=kenna_api_key_check kenna_api_key=$API_TOKEN
