name: User Audit
# syntax for a schedule. Uncomment next 3 lines to use schedules. This sample will run everyday at 5:45 UTC
#on: 
#  schedule:
#    - cron: "45 5 * * *"  

# default syntax is an on-demand task that can be manually initiated 
on: workflow_dispatch
jobs:
  user_audit_job:
    build:
      runs-on: ubuntu-latest
      env: API_TOKEN: ${{ secrets.API_KEY }}
    steps:
     - run: |
      pip install -r requirements.txt
      python useraudit.py $API_TOKEN
